### ISSUE TITLE
Convert to noarch

### ISSUE THREAD

**Issue by dhohn** [conda-forge/requirements-detector-feedstock#16]
### Comment:

Can this package be converted to noarch? AFAICS that should be straightforward.

**Comment by jakirkham** [comment]
Please feel free to give it a try

**Comment by valeriupredoi** [comment]
that'd be great if you did that @dhohn - and toss in support for Python 3.11 as well while you at it, please, mate! If not, let me know, I'll at least try rebuild for Python 3.11 - @jakirkham this is holding up prospector from Python 3.11, which in turn, is holding up a few other packages :grin: :snake:

**Comment by dhohn** [comment]
I haven't had time to make myself familiar with all this feedstock/smithy stuff yet. Unfortunately its also fairly low on my list, so I wont get around to it so soon.
